server:
  port: 53010
#  error:
#    whitelabel:
#      enabled: true

spring:
##################### DB #####################
  datasource:
    url: jdbc:mysql://123.207.54.159:3306/micro-req?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Mysql7456321.

#    url: jdbc:mysql://127.0.0.1:3306/micro-req?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: 1122
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    

            
logging: 
  config: classpath:log4j2-dev.xml
  
swagger: 
  enable: true


